baseURL = "http://example.org/"
languageCode = "en-us"
title = "Palermo Penano's Site"
theme = "xmin"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    description = "A website built through Hugo and blogdown."
    footer = "© 2020 Palermo Penano. Powered by Hugo using the [XMin](https://github.com/yihui/hugo-xmin) theme"